In [1]:
import numpy as np

In [2]:
from sklearn.cluster import AgglomerativeClustering, KMeans, DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.manifold import MDS

In [3]:
data = np.array([
    [-1, -1],
    [-2, -1],
    [-1, -2],
    [0, 0],
    [2, 1],
    [2, 3]
])

**1**

In [4]:
aggl_cl = AgglomerativeClustering(n_clusters=2, linkage='single').fit(data)

In [5]:
aggl_cl.labels_

array([1, 1, 1, 1, 0, 0], dtype=int64)

**2**

In [6]:
init_clusters = data[(0,3), :]
init_clusters

array([[-1, -1],
       [ 0,  0]])

In [7]:
kmeans = KMeans(n_clusters=2, init = init_clusters, n_init=1).fit(data)
kmeans.n_iter_

2

In [8]:
kmeans.labels_

array([0, 0, 0, 1, 1, 1])

**3**

In [9]:
eps = 2
m = 3
dbscan = DBSCAN(eps=eps, min_samples=m).fit(data)
dbscan.labels_

array([ 0,  0,  0,  0, -1, -1], dtype=int64)

**4**

**5**

In [10]:
labels = [0, 0, 0, 1, 1, 1]
silhouette_score(data, labels)

0.45993283428643883

**6**

In [11]:
pca = PCA(n_components=1).fit(data)

In [12]:
pca.components_

array([[0.67944959, 0.73372219]])

**7**

In [13]:
pca.transform(data)[5]

array([3.56006575])

**8**

In [14]:
mds = MDS(n_components=1, n_init=100).fit(data)
mds.embedding_

array([[-1.33662747],
       [-2.46321196],
       [-1.9825745 ],
       [ 0.00745504],
       [ 2.09273265],
       [ 3.68222624]])

In [15]:
mds.n_iter_

3